### ISSUE TITLE
When in 'use strict' mode this points to undefined

### ISSUE THREAD

**Issue by luc4leone** [gordonmzhu/cheatsheet-js#3]
Hi Gordon, 

When in `'use strict'` mode `this` points to `undefined`.

I saw you talking about this exception to case 1 of your 'Understanding this' document  in an old office hour video, maybe you want to integrate the doc?

**Comment by gordonmzhu** [comment]
Ohhhh thanks Luca. Just fixed this issue today. Thanks for pointing it out! And thanks for inspiring the `boundOnce` example as well!
